import { describe, expect, it } from "vitest";
import { channelLayoutOf } from "./channelLayout";

const BITS: Readonly<Record<string, number>> = {
	FL: 0x1,
	FR: 0x2,
	FC: 0x4,
	LFE: 0x8,
	BL: 0x10,
	BR: 0x20,
	FLC: 0x40,
	FRC: 0x80,
	BC: 0x100,
	SL: 0x200,
	SR: 0x400,
	TC: 0x800,
	TFL: 0x1000,
	TFC: 0x2000,
	TFR: 0x4000,
	TBL: 0x8000,
	TBC: 0x10000,
	TBR: 0x20000,
};

const ACCEPTED_LAYOUTS: ReadonlyArray<readonly [string, string]> = [
	["mono", "FC"],
	["stereo", "FL+FR"],
	["2.1", "FL+FR+LFE"],
	["3.0", "FL+FR+FC"],
	["3.0(back)", "FL+FR+BC"],
	["4.0", "FL+FR+FC+BC"],
	["quad", "FL+FR+BL+BR"],
	["quad(side)", "FL+FR+SL+SR"],
	["3.1", "FL+FR+FC+LFE"],
	["5.0", "FL+FR+FC+BL+BR"],
	["5.0(side)", "FL+FR+FC+SL+SR"],
	["4.1", "FL+FR+FC+LFE+BC"],
	["5.1", "FL+FR+FC+LFE+BL+BR"],
	["5.1(side)", "FL+FR+FC+LFE+SL+SR"],
	["6.0", "FL+FR+FC+BC+SL+SR"],
	["6.0(front)", "FL+FR+FLC+FRC+SL+SR"],
	["3.1.2", "FL+FR+FC+LFE+TFL+TFR"],
	["hexagonal", "FL+FR+FC+BL+BR+BC"],
	["6.1", "FL+FR+FC+LFE+BC+SL+SR"],
	["6.1(back)", "FL+FR+FC+LFE+BL+BR+BC"],
	["6.1(front)", "FL+FR+LFE+FLC+FRC+SL+SR"],
	["7.0", "FL+FR+FC+BL+BR+SL+SR"],
	["7.0(front)", "FL+FR+FC+FLC+FRC+SL+SR"],
	["7.1", "FL+FR+FC+LFE+BL+BR+SL+SR"],
	["7.1(wide)", "FL+FR+FC+LFE+BL+BR+FLC+FRC"],
	["7.1(wide-side)", "FL+FR+FC+LFE+FLC+FRC+SL+SR"],
	["5.1.2", "FL+FR+FC+LFE+SL+SR+TFL+TFR"],
	["5.1.2(back)", "FL+FR+FC+LFE+BL+BR+TFL+TFR"],
	["octagonal", "FL+FR+FC+BL+BR+BC+SL+SR"],
	["cube", "FL+FR+BL+BR+TFL+TFR+TBL+TBR"],
	["5.1.4", "FL+FR+FC+LFE+SL+SR+TFL+TFR+TBL+TBR"],
	["7.1.2", "FL+FR+FC+LFE+BL+BR+SL+SR+TFL+TFR"],
	["7.1.4", "FL+FR+FC+LFE+BL+BR+SL+SR+TFL+TFR+TBL+TBR"],
	["9.1.4", "FL+FR+FC+LFE+BL+BR+FLC+FRC+SL+SR+TFL+TFR+TBL+TBR"],
];

describe("channelLayoutOf", () => {
	it.each(ACCEPTED_LAYOUTS)("gives %s the sum of its decomposition's bits", (name, decomposition) => {
		const channels = decomposition.split("+");
		const mask = channels.reduce((sum, channel) => sum + (BITS[channel] ?? Number.NaN), 0);

		expect(channelLayoutOf(name)).toEqual({ name, channelCount: channels.length, channelMask: mask });
	});

	it.each([
		["mono", 1, 0x4],
		["stereo", 2, 0x3],
		["5.1", 6, 0x3f],
		["5.1(side)", 6, 0x60f],
		["7.1", 8, 0x63f],
		["7.1.4", 12, 0x2d63f],
		["9.1.4", 14, 0x2d6ff],
		["FL+FR+LFE", 3, 0xb],
		["0x3f", 6, 0x3f],
		["63", 6, 0x3f],
		["+63", 6, 0x3f],
		["0X3F", 6, 0x3f],
		[" 63", 6, 0x3f],
		["063", 4, 0x33],
		["0x3fC", 8, 0x3fc],
		["6C", 6, 0],
		["+6C", 6, 0],
		["06C", 6, 0],
		[" 6C", 6, 0],
		["6 channels", 6, 0],
		["6 channels (FL+FR+FC+LFE+BL+BR)", 6, 0x3f],
		["6 channels(FL+FR+FC+LFE+BL+BR)", 6, 0x3f],
		["6 channels ( FL+FR+FC+LFE+BL+BR )", 6, 0x3f],
		["2channels(FL+FR)", 2, 0x3],
		["2  channels(FL+FR)", 2, 0x3],
		["2 channels ( FL+FR )", 2, 0x3],
		[" 2 channels (FL+FR)", 2, 0x3],
		["+2 channels (FL+FR)", 2, 0x3],
		[" FL + FR ", 2, 0x3],
		["FL+FR+", 2, 0x3],
		["'FL'+FR", 2, 0x3],
		["USR0+USR1", 2, 0x3],
		["USR0x1", 1, 0x2],
		["USR01", 1, 0x2],
		["USR17", 1, 0x20000],
		["USR", 1, 0x1],
		["FL+USR1+USR0x4", 3, 0x13],
		["2 channels (USR0+USR1)", 2, 0x3],
		["FL@+FR", 2, 0x3],
		["FL@+FR@", 2, 0x3],
		["UNK", 1, 0],
		["UNK+UNK", 2, 0],
		["UNK@+UNK", 2, 0],
	])("reads %j as %i channels with mask %i", (value, channelCount, channelMask) => {
		expect(channelLayoutOf(value)).toEqual({ name: value, channelCount, channelMask });
	});

	it.each([
		"0",
		"0x0",
		"+FL+FR",
		"FL++FR",
		"2 channels (FL+FR",
		"2 channels (FL+FR) ",
		"3 channels (FL+FR)",
		"5 channels (FL+FR)",
		"6 C",
		"6  channels",
		"6 channels ",
		" stereo",
		"FL@a+FR",
		"UNK+FL",
		"ambisonic 1",
		"63 ",
		"6channels",
		"7.2.3",
		"9.1.6",
		"hexadecagonal",
		"binaural",
		"downmix",
		"22.2",
		"FR+FL",
		"FL+FL",
		"FL+FR+DL",
		"USR63",
		"USR18",
		"USR-1",
		"USR08",
		"USR1x",
		"FL+USR0",
		"UNK@a",
		"UNK+UNSD",
		"stereo+LFE",
		"fl+fr",
		"0x40000",
		"6c",
		"",
	])("rejects %j", (value) => {
		expect(() => channelLayoutOf(value)).toThrow(
			`Unsupported channel layout "${value}": use a standard layout or channel names joined by + within the WAVE channel mask, such as 5.1 or FL+FR+LFE, a channel mask such as 0x3f, or a channel count such as 6C`,
		);
	});
});
